# Generated by Django 4.1.3 on 2022-11-28 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0012_order_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 13, 3, 24, 631345, tzinfo=datetime.timezone.utc), verbose_name='date and time of the creation'),
            preserve_default=False,
        ),
    ]
