# Generated by Django 4.1.3 on 2022-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0013_order_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_datetime',
            field=models.CharField(blank=True, max_length=100, verbose_name='date and time of the creation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_datetime',
            field=models.CharField(blank=True, max_length=100, verbose_name='date and time of the delivery'),
        ),
    ]
